/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import classebasica.Paciente;
import classebasica.PlanodeSaude;
import negocios.NegocioRegistroPaciente;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class RegistroPaciente extends javax.swing.JFrame {
    Paciente p = new Paciente();
    PlanodeSaude ps = new PlanodeSaude();
    NegocioRegistroPaciente nrp = new NegocioRegistroPaciente();
    ArrayList<Paciente> listSexo;
    /**
     * Creates new form Registropaciente
     */

    public RegistroPaciente() {
        initComponents();
        mostrarSexoComboBox();
        mostrarPlanodesaudeComboBox();
        jTextFieldNomePaciente.setDocument(new classebasica.LetrasPermitidas());
        jTextFieldCpf.setDocument(new classebasica.NumerosPermitidos());
        jTextFieldCpfR.setDocument(new classebasica.NumerosPermitidos());
    }

    private void mostrarPlanodesaudeComboBox() {
        try {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
                ArrayList<Paciente> listPlanodesaude = nrp.listPlanodeSaude();
            for (Paciente p : listPlanodesaude) {
                modelo.addElement(p.getPlanodeSaude().getNomePlano());
            }
            jComboBoxPlanoPaciente.setModel(modelo);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    private void mostrarSexoComboBox() {
        try {
            listSexo = nrp.listarsexo();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < listSexo.size(); i++) {
                Paciente p = listSexo.get(i);
                modelo.addElement(p.getSexo().getNome_Sexo());
            }
            jComboBoxSexoPaciente.setModel(modelo);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
private void LimparTela() {
            try {
          //Botao limpar
        jTextFieldNomePaciente.setText("");
        jTextFieldCpf.setText("");
        jFormattedTextFieldNascimentoPaciente.setText("");
        jTextFieldCpfR.setText("");
                } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButtonRemoverPaciente = new javax.swing.JButton();
        jButtonListarPaciente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaPaciente = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxPlanoPaciente = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxSexoPaciente = new javax.swing.JComboBox();
        jButtonOKPaciente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldNascimentoPaciente = new javax.swing.JFormattedTextField();
        jTextFieldCpfR = new javax.swing.JTextField();
        jTextFieldNomePaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro do Paciente");

        jLabel6.setText("Para removido digite o CPF:");

        jButtonRemoverPaciente.setText("Remover");
        jButtonRemoverPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPacienteActionPerformed(evt);
            }
        });

        jButtonListarPaciente.setText("Atualizar Listagem");
        jButtonListarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPacienteActionPerformed(evt);
            }
        });

        jTableTabelaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        try {
            ListarPaciente();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        jScrollPane1.setViewportView(jTableTabelaPaciente);

        jLabel5.setText("Plano de saude:");

        jComboBoxPlanoPaciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Escolha-" }));
        jComboBoxPlanoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlanoPacienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel4.setText("Data de Nascimento:");

        jTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpfActionPerformed(evt);
            }
        });

        jLabel3.setText("Sexo:");

        jComboBoxSexoPaciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Escolha-" }));
        jComboBoxSexoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoPacienteActionPerformed(evt);
            }
        });

        jButtonOKPaciente.setText("OK");
        jButtonOKPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKPacienteActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF:");

        try {
            jFormattedTextFieldNascimentoPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNascimentoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNascimentoPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonListarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxPlanoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCpfR))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jFormattedTextFieldNascimentoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))))
                            .addComponent(jTextFieldNomePaciente))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRemoverPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOKPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPlanoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOKPaciente)
                    .addComponent(jFormattedTextFieldNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarPaciente)
                    .addComponent(jLabel6)
                    .addComponent(jButtonRemoverPaciente)
                    .addComponent(jTextFieldCpfR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldNascimentoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNascimentoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNascimentoPacienteActionPerformed

    private void jButtonOKPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKPacienteActionPerformed
        // TODO add your handling code here:
        try {
            p.setNome(jTextFieldNomePaciente.getText());
            p.setCpf_Paciente(jTextFieldCpf.getText());
            p.setDataNasimento(jFormattedTextFieldNascimentoPaciente.getText());
            int posicaoselecionadaSexo = jComboBoxSexoPaciente.getSelectedIndex();
            String posicaoselecionadaPlano = String.valueOf(jComboBoxPlanoPaciente.getSelectedIndex());
            p.getSexo().setCod_Sexo(posicaoselecionadaSexo);
            p.getPlanodeSaude().setCodPlano(posicaoselecionadaPlano);
            nrp.cadastrar(p);
            LimparTela();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonOKPacienteActionPerformed

    private void jComboBoxSexoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoPacienteActionPerformed

    private void jTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCpfActionPerformed
    private void ListarPaciente() {
        try {
            // TODO add your handling code here:
            ArrayList<Paciente> listap = nrp.listarPaciente();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"CPF", "Nome", "Sexo", "Data de Nascimento", "Plano de Saúde"});
            for (Paciente p : listap) {
                modelo.addRow(new String[]{p.getCpf_Paciente() + "", p.getNome() + "", p.getSexo().getNome_Sexo() + "", p.getDataNasimento() + "", p.getPlanodeSaude().getNomePlano()});
            }
            jTableTabelaPaciente.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    private void jButtonListarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPacienteActionPerformed
        // TODO add your handling code here:
         try {
        ListarPaciente();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonListarPacienteActionPerformed

    private void jComboBoxPlanoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlanoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPlanoPacienteActionPerformed

    private void jButtonRemoverPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPacienteActionPerformed
                try {
        int resp = JOptionPane.showConfirmDialog(null, "Voce deseja remover o Paciente?", "Remover Paciente", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
        p.setCpf_Paciente (jTextFieldCpfR.getText()); 
        nrp.remover(p);
        LimparTela();
        ListarPaciente();
    }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jButtonRemoverPacienteActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListarPaciente;
    private javax.swing.JButton jButtonOKPaciente;
    private javax.swing.JButton jButtonRemoverPaciente;
    private javax.swing.JComboBox jComboBoxPlanoPaciente;
    private javax.swing.JComboBox jComboBoxSexoPaciente;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimentoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaPaciente;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldCpfR;
    private javax.swing.JTextField jTextFieldNomePaciente;
    // End of variables declaration//GEN-END:variables

}
