package apresentacao;

import classebasica.Medico;
import negocios.NegocioRegistroMedico;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MegaKingBR
 */
public class RegistroMedico extends javax.swing.JFrame {
    Medico m = new Medico();
    NegocioRegistroMedico nrm = new NegocioRegistroMedico();
    ArrayList<Medico> listEspecialidades; 
    ArrayList<Medico> listSexo; 
    /**
     * Creates new form NewJFrame
     */
    public RegistroMedico() {
        initComponents();
        mostrarSexoComboBox();
        mostrarEspecialidadesComboBox();
        jTextFieldNomeMedico.setDocument(new classebasica.LetrasPermitidas());
        jTextFieldCrm.setDocument(new classebasica.NumerosPermitidos());
        jTextFieldCrmR.setDocument(new classebasica.NumerosPermitidos());
    }
    private void mostrarEspecialidadesComboBox(){
        try {
            listEspecialidades = nrm.listEspecialidades();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < listEspecialidades.size(); i++) {
                Medico m = listEspecialidades.get(i);
                modelo.addElement(m.getEspecialidade().getNomeEspecialidade());
            }
            jComboBoxEspecialidadeMedico.setModel(modelo);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    private void mostrarSexoComboBox(){
        try {
            listSexo = nrm.listarsexo();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < listSexo.size(); i++) {
                Medico m = listSexo.get(i);
                modelo.addElement(m.getSexo().getNome_Sexo());
            }
            jComboBoxSexoMedico.setModel(modelo);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }    
    private void ListarMedico() {
        try {
            // TODO add your handling code here:
            ArrayList<Medico> listamedico = nrm.listarmedico();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"CRM", "Nome", "Sexo", "Data de Nascimento", "Especialidade"});
            for (Medico m : listamedico) {
                modelo.addRow(new String[]{m.getCrm_Medico() + "", m.getNome() + "", m.getSexo().getNome_Sexo() + "", m.getDataNasimento() + "", m.getEspecialidade().getNomeEspecialidade()});
            }
            jTableTabelaMedico.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
private void LimparTela() {
          //Botao limpar
        jTextFieldNomeMedico.setText("");
        jTextFieldCrm.setText("");
        jFormattedTextFieldNascimentoMedico.setText("");
        jTextFieldCrmR.setText("");

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonOKMedico = new javax.swing.JButton();
        jComboBoxSexoMedico = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxEspecialidadeMedico = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaMedico = new javax.swing.JTable();
        jButtonRemoverMedico = new javax.swing.JButton();
        jButtonListarMedico = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldNascimentoMedico = new javax.swing.JFormattedTextField();
        jTextFieldCrmR = new javax.swing.JTextField();
        jTextFieldCrm = new javax.swing.JTextField();
        jTextFieldNomeMedico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro do Medico");

        jLabel1.setText("Nome:");

        jButtonOKMedico.setText("OK");
        jButtonOKMedico.setNextFocusableComponent(jButtonListarMedico);
        jButtonOKMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKMedicoActionPerformed(evt);
            }
        });

        jComboBoxSexoMedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Escolha-" }));
        jComboBoxSexoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoMedicoActionPerformed(evt);
            }
        });

        jLabel3.setText("Sexo:");

        jLabel2.setText("CRM:");

        jLabel4.setText("Data de Nascimento:");

        jLabel5.setText("Especialidade:");

        jComboBoxEspecialidadeMedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Escolha-" }));
        jComboBoxEspecialidadeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspecialidadeMedicoActionPerformed(evt);
            }
        });

        jTableTabelaMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ListarMedico();
        jScrollPane1.setViewportView(jTableTabelaMedico);

        jButtonRemoverMedico.setText("Remover");
        jButtonRemoverMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverMedicoActionPerformed(evt);
            }
        });

        jButtonListarMedico.setText("Atualizar Listagem");
        jButtonListarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarMedicoActionPerformed(evt);
            }
        });

        jLabel6.setText("Para removido digite o CRM:");

        try {
            jFormattedTextFieldNascimentoMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jFormattedTextFieldNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNomeMedico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCrm))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonListarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEspecialidadeMedico, 0, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBoxSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jTextFieldCrmR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonRemoverMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonOKMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(373, 373, 373)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEspecialidadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOKMedico)
                    .addComponent(jFormattedTextFieldNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarMedico)
                    .addComponent(jLabel6)
                    .addComponent(jButtonRemoverMedico)
                    .addComponent(jTextFieldCrmR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKMedicoActionPerformed
    // TODO add your handling code here:
            try {        
        m.setNome (jTextFieldNomeMedico.getText());
        m.setCrm_Medico (jTextFieldCrm.getText());
        m.setDataNasimento(jFormattedTextFieldNascimentoMedico.getText());
        int posicaoselecionadaSexo = jComboBoxSexoMedico.getSelectedIndex();
        String posicaoselecionadaEspecialidade = String.valueOf(jComboBoxEspecialidadeMedico.getSelectedIndex());
        m.getSexo().setCod_Sexo(posicaoselecionadaSexo);
        m.getEspecialidade().setCodEspecialidade(posicaoselecionadaEspecialidade);
        nrm.cadastrar(m); 
        LimparTela();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonOKMedicoActionPerformed

    private void jComboBoxEspecialidadeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspecialidadeMedicoActionPerformed
                   // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEspecialidadeMedicoActionPerformed

    private void jButtonRemoverMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverMedicoActionPerformed
        try {
        int resp = JOptionPane.showConfirmDialog(null, "Voce deseja remover o Medico?", "Remover Medico", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
        m.setCrm_Medico (jTextFieldCrmR.getText()); 
        nrm.remover(m);
        ListarMedico();
        LimparTela();
    }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jButtonRemoverMedicoActionPerformed

    private void jButtonListarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarMedicoActionPerformed
        // TODO add your handling code here:
        ListarMedico();
    }//GEN-LAST:event_jButtonListarMedicoActionPerformed

    private void jComboBoxSexoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoMedicoActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListarMedico;
    private javax.swing.JButton jButtonOKMedico;
    private javax.swing.JButton jButtonRemoverMedico;
    private javax.swing.JComboBox jComboBoxEspecialidadeMedico;
    private javax.swing.JComboBox jComboBoxSexoMedico;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimentoMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaMedico;
    private javax.swing.JTextField jTextFieldCrm;
    private javax.swing.JTextField jTextFieldCrmR;
    private javax.swing.JTextField jTextFieldNomeMedico;
    // End of variables declaration//GEN-END:variables

}
