/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import classebasica.PlanodeSaude;
import negocios.NegocioRegistroPlanodeSaude;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MegaKingBR
 */
public class RegistroPlanodeSaude extends javax.swing.JFrame {
        PlanodeSaude ps = new PlanodeSaude();
        NegocioRegistroPlanodeSaude nrps = new NegocioRegistroPlanodeSaude();
    /**
     * Creates new form RegistroPlanodeSaude
     */
    public RegistroPlanodeSaude() {
        initComponents();
        jTextFieldCodPlano.setDocument(new classebasica.NumerosPermitidos());
        jTextFieldNomePlano.setDocument(new classebasica.LetrasPermitidas());
        jTextFieldRemoverPlano.setDocument(new classebasica.NumerosPermitidos());
    }
    private void listar() {
        try {
            // TODO add your handling code here:
            ArrayList<PlanodeSaude> lista = nrps.listPlanodeSaude();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"Codigo Especialidade", "Nome Especialidade"});
            for (PlanodeSaude ps : lista) {
                modelo.addRow(new String[]{ps.getCodPlano() + "", ps.getNomePlano()});
            }
            jTableTabelaPlano.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    } 
private void LimparTela() {
          //Botao limpar
    try {
        jTextFieldCodPlano.setText("");
        jTextFieldNomePlano.setText("");
        jTextFieldRemoverPlano.setText("");
    } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaPlano = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonListarPlanos = new javax.swing.JButton();
        jButtonOKPlano = new javax.swing.JButton();
        jButtonRemoverPlano = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRemoverPlano = new javax.swing.JTextField();
        jTextFieldNomePlano = new javax.swing.JTextField();
        jTextFieldCodPlano = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Plano de Súde");

        jTableTabelaPlano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listar();
        jScrollPane1.setViewportView(jTableTabelaPlano);

        jLabel1.setText("Codigo do Plano de saúde:");

        jLabel2.setText("Nome do Plano de saúde:");

        jButtonListarPlanos.setText("Atualizar Listagem");
        jButtonListarPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPlanosActionPerformed(evt);
            }
        });

        jButtonOKPlano.setText("OK");
        jButtonOKPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKPlanoActionPerformed(evt);
            }
        });

        jButtonRemoverPlano.setText("Remover");
        jButtonRemoverPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPlanoActionPerformed(evt);
            }
        });

        jLabel3.setText("Para remover o Plano de Saúde insira o codido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRemoverPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoverPlano, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNomePlano)
                            .addComponent(jTextFieldCodPlano, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOKPlano, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jButtonListarPlanos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOKPlano)
                    .addComponent(jTextFieldCodPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarPlanos)
                    .addComponent(jTextFieldNomePlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoverPlano)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldRemoverPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPlanosActionPerformed
    listar();    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListarPlanosActionPerformed

    private void jButtonOKPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKPlanoActionPerformed
             try {        
        ps.setNomePlano(jTextFieldNomePlano.getText());
        ps.setCodPlano (jTextFieldCodPlano.getText());
        NegocioRegistroPlanodeSaude nps = new NegocioRegistroPlanodeSaude();
        nrps.cadastrar(ps); 
        LimparTela();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }       
    }//GEN-LAST:event_jButtonOKPlanoActionPerformed

    private void jButtonRemoverPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPlanoActionPerformed

        try {
        int resp = JOptionPane.showConfirmDialog(null, "Voce deseja remover o Paciente?", "Remover Paciente", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
        ps.setCodPlano (jTextFieldRemoverPlano.getText());
        nrps.remover(ps);
        LimparTela();
        listar();
    }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }     
    }//GEN-LAST:event_jButtonRemoverPlanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPlanodeSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPlanodeSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPlanodeSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPlanodeSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPlanodeSaude().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListarPlanos;
    private javax.swing.JButton jButtonOKPlano;
    private javax.swing.JButton jButtonRemoverPlano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaPlano;
    private javax.swing.JTextField jTextFieldCodPlano;
    private javax.swing.JTextField jTextFieldNomePlano;
    private javax.swing.JTextField jTextFieldRemoverPlano;
    // End of variables declaration//GEN-END:variables
}
