/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import classebasica.Consulta;
import classebasica.Medico;
import classebasica.Paciente;
import negocios.NegocioRegistroMedico;
import negocios.NegocioRegistroPaciente;
import negocios.NegocioTeladeConsulta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MegaKingBR
 */
public class TeladeConsulta extends javax.swing.JFrame {
    Consulta c =new Consulta();
    Paciente p = new Paciente();
    Medico m = new Medico();
    ArrayList<Consulta> listaprontuario;
    /**
     * Creates new form TeladeConsulta1
     */
    public TeladeConsulta() {
        initComponents();
        jTextFieldCpfPaciente.setDocument(new classebasica.NumerosPermitidos());
        jTextFieldCrmMedico.setDocument(new classebasica.NumerosPermitidos());
        jTextFieldProntuario.setDocument(new classebasica.NumerosPermitidos());
    }
    private void ListarProntuario() {
        try {
            NegocioTeladeConsulta ntc = new NegocioTeladeConsulta();
            listaprontuario = ntc.listarProntuario();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"Numero do Prontúario", "CPF do paciente", "Nome do paciente", "Plano de Saúde", "Nome do Medico", "Especialidade","Data da consulta", "Hora Inicio", "Hora Termino"});
            for (Consulta c : listaprontuario) {
                modelo.addRow(new String[]{c.getNumeroProntuario() + "", c.getPaciente().getCpf_Paciente() + "", c.getPaciente().getNome() + "", c.getPaciente().getPlanodeSaude().getNomePlano() + "", 
                c.getMedico().getNome() + "", c.getMedico().getEspecialidade().getNomeEspecialidade() + "", c.getDataConsulta()+ "", c.getHoraInicio() + "", c.getHoraFinal()});
            }
            jTableListagem.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }    
    }
    private void ListarMedico() {
        try {
            NegocioRegistroMedico nrm = new NegocioRegistroMedico();    
            ArrayList<Medico> listamedico = nrm.listarmedico();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"CRM", "Nome", "Sexo", "Data de Nascimento", "Especialidade"});
            for (Medico m : listamedico) {
                modelo.addRow(new String[]{m.getCrm_Medico() + "", m.getNome() + "", m.getSexo().getNome_Sexo() + "", m.getDataNasimento() + "", m.getEspecialidade().getNomeEspecialidade()});
            }
            jTableListagem.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    private void ListarPaciente() {
        try {
        NegocioRegistroPaciente nrp = new NegocioRegistroPaciente();
            ArrayList<Paciente> listap = nrp.listarPaciente();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"CPF", "Nome", "Sexo", "Data de Nascimento", "Plano de Saúde"});
            for (Paciente p : listap) {
                modelo.addRow(new String[]{p.getCpf_Paciente() + "", p.getNome() + "", p.getSexo().getNome_Sexo() + "", p.getDataNasimento() + "", p.getPlanodeSaude().getNomePlano()});
            }
            jTableListagem.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
private void LimparTela() {
          //Botao limpar
    try {
        jTextFieldCpfPaciente.setText("");
        jLabelNomePaciente.setText("");
        jLabePlanodeSaude.setText("");
        jTextFieldCrmMedico.setText("");
        jLabelNomeMedico.setText("");
        jLabelEspecialidade.setText("");
        jFormattedTextFieldDataConsulta.setText("");
        jFormattedTextFieldHoraInicio.setText("");
        jFormattedTextFieldHoraFinal.setText("");
        jTextAreaRelatorio.setText("");
        jTextFieldProntuario.setText("");
    } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRelatorio = new javax.swing.JTextArea();
        jButtonOK = new javax.swing.JButton();
        jButtonListagemProntuario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListagem = new javax.swing.JTable();
        jButtonListagemMedico = new javax.swing.JButton();
        jButtonListagemPaciente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonMostrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonRemoverProntuario = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelNomePaciente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelEspecialidade = new javax.swing.JLabel();
        jLabePlanodeSaude = new javax.swing.JLabel();
        jTextFieldCpfPaciente = new javax.swing.JTextField();
        jButtonAtualizarProntuario = new javax.swing.JButton();
        jLabelNomeMedico = new javax.swing.JLabel();
        jTextFieldCrmMedico = new javax.swing.JTextField();
        jFormattedTextFieldDataConsulta = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHoraInicio = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHoraFinal = new javax.swing.JFormattedTextField();
        jTextFieldProntuario = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemRegistroMedico = new javax.swing.JMenuItem();
        jMenuItemRegistroPaciente = new javax.swing.JMenuItem();
        jMenuItemRegistroEspecialidade = new javax.swing.JMenuItem();
        jMenuItemRegistroPlanodeSaude = new javax.swing.JMenuItem();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("CPF:");

        jLabel4.setText("Nome do médico:");

        jLabel1.setText("Data da consulta:");

        jLabel5.setText(" Hora do Inicio da consulta:");

        jLabel6.setText("Hora do termino da consulta:");

        jLabel7.setText("RELÁTORIO MÉDICO:");

        jTextAreaRelatorio.setColumns(20);
        jTextAreaRelatorio.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRelatorio);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonListagemProntuario.setText("Listagem de Prontuario");
        jButtonListagemProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListagemProntuarioActionPerformed(evt);
            }
        });

        jLabel9.setText("Listagem de prontuários, medicos e pacientes:");

        jTableListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableListagem);
        ListarProntuario();

        jButtonListagemMedico.setText("Listagem de Medicos");
        jButtonListagemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListagemMedicoActionPerformed(evt);
            }
        });

        jButtonListagemPaciente.setText("Listagem de Pacientes");
        jButtonListagemPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListagemPacienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Especialidade");

        jButtonMostrar.setText("Mostrar Prontúario");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jLabel11.setText("-");

        jLabel12.setText("Numero do Prontuario:");

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonRemoverProntuario.setText("Remover");
        jButtonRemoverProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverProntuarioActionPerformed(evt);
            }
        });

        jLabel13.setText("-");

        jLabel14.setText("-");

        jLabel15.setText("Nome do paciente:");

        jLabelNomePaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("CRM:");

        jLabel18.setText("Plano de Saúde");

        jLabelEspecialidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabePlanodeSaude.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldCpfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpfPacienteActionPerformed(evt);
            }
        });
        jTextFieldCpfPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCpfPacienteFocusLost(evt);
            }
        });

        jButtonAtualizarProntuario.setText("Atualizar Prontuario");
        jButtonAtualizarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarProntuarioActionPerformed(evt);
            }
        });

        jLabelNomeMedico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldCrmMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrmMedicoActionPerformed(evt);
            }
        });
        jTextFieldCrmMedico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCrmMedicoFocusLost(evt);
            }
        });

        try {
            jFormattedTextFieldDataConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldHoraFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jMenu1.setText("Arquivos");

        jMenuItemRegistroMedico.setText("Registro Medico");
        jMenuItemRegistroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRegistroMedico);

        jMenuItemRegistroPaciente.setText("Registro Paciente");
        jMenuItemRegistroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroPacienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRegistroPaciente);

        jMenuItemRegistroEspecialidade.setText("Registro Especialidade");
        jMenuItemRegistroEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroEspecialidadeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRegistroEspecialidade);

        jMenuItemRegistroPlanodeSaude.setText("Registro Plano de Saúde");
        jMenuItemRegistroPlanodeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroPlanodeSaudeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRegistroPlanodeSaude);

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSobre);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                        .addGap(83, 83, 83)
                        .addComponent(jButtonListagemProntuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListagemMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListagemPaciente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCrmMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabelNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEspecialidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabePlanodeSaude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jFormattedTextFieldDataConsulta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldHoraInicio))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jFormattedTextFieldHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemoverProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAtualizarProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jButtonListagemProntuario)
                            .addComponent(jButtonListagemMedico)
                            .addComponent(jButtonListagemPaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel18))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabePlanodeSaude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelNomePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCpfPaciente))
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEspecialidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNomeMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCrmMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonMostrar)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonRemoverProntuario)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jButtonAtualizarProntuario)
                    .addComponent(jTextFieldProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        JOptionPane.showMessageDialog(null, "Desenvolvido por:\n Fábio José Lucena");
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemRegistroPlanodeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroPlanodeSaudeActionPerformed
       try {
        RegistroPlanodeSaude jFrameRegistroPlanodeSaude = new RegistroPlanodeSaude();
        jFrameRegistroPlanodeSaude.setLocationRelativeTo(null);
        jFrameRegistroPlanodeSaude.setVisible(true);   
        jFrameRegistroPlanodeSaude.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);  
            } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemRegistroPlanodeSaudeActionPerformed

    private void jMenuItemRegistroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroPacienteActionPerformed
        try {
        RegistroPaciente jFrameRegistropaciente = new RegistroPaciente();
        jFrameRegistropaciente.setLocationRelativeTo(null);
        jFrameRegistropaciente.setVisible(true);   
        jFrameRegistropaciente.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemRegistroPacienteActionPerformed

    private void jMenuItemRegistroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroMedicoActionPerformed
        try {
        RegistroMedico jFrameRegistromedico = new RegistroMedico();
        jFrameRegistromedico.setLocationRelativeTo(null);
        jFrameRegistromedico.setVisible(true); 
        jFrameRegistromedico.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemRegistroMedicoActionPerformed

    private void jButtonListagemProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListagemProntuarioActionPerformed
        try {
        ListarProntuario();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonListagemProntuarioActionPerformed

    private void jButtonListagemPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListagemPacienteActionPerformed
try {
        ListarPaciente();
} catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonListagemPacienteActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        try {    
            c.setNumeroProntuario(jTextFieldProntuario.getText());
            c.getPaciente().setCpf_Paciente(jTextFieldCpfPaciente.getText());
            c.getMedico().setCrm_Medico(jTextFieldCrmMedico.getText());
            c.setDataConsulta(jFormattedTextFieldDataConsulta.getText());
            c.setHoraInicio(jFormattedTextFieldHoraInicio.getText());
            c.setHoraFinal(jFormattedTextFieldHoraFinal.getText());
            c.setDescricaoConsulta(jTextAreaRelatorio.getText());  
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    try {
        NegocioTeladeConsulta ntc = new NegocioTeladeConsulta();
        ntc.cadastrar(c);
            jTextFieldCpfPaciente.setText("");
            jLabelNomePaciente.setText("");
            jLabePlanodeSaude.setText("");
            jTextFieldCrmMedico.setText("");
            jLabelNomeMedico.setText("");
            jLabelEspecialidade.setText("");
            jFormattedTextFieldDataConsulta.setText("");
            jFormattedTextFieldHoraInicio.setText("");
            jFormattedTextFieldHoraFinal.setText("");
            jTextAreaRelatorio.setText("");
            jTextFieldProntuario.setText("");
            ListarProntuario();
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonListagemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListagemMedicoActionPerformed
try {
        ListarMedico();
}
    catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jButtonListagemMedicoActionPerformed

    private void jMenuItemRegistroEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroEspecialidadeActionPerformed
try {
        RegistroEspecialidade jFrameRegistroEspecialidade = new RegistroEspecialidade();
        jFrameRegistroEspecialidade.setLocationRelativeTo(null);
        jFrameRegistroEspecialidade.setVisible(true);
        jFrameRegistroEspecialidade.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
}catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jMenuItemRegistroEspecialidadeActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
try {
        LimparTela();
}catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jButtonLimparActionPerformed
            private void mostrarProntuario() {
        try {
            c.setNumeroProntuario(jTextFieldProntuario.getText());
            NegocioTeladeConsulta ntc = new NegocioTeladeConsulta();
            ntc.MostraProntuario(c);
            jLabelNomePaciente.setText(c.getPaciente().getNome());
            jTextFieldCpfPaciente.setText(c.getPaciente().getCpf_Paciente());
            jLabePlanodeSaude.setText(c.getPaciente().getPlanodeSaude().getNomePlano());
            jTextFieldCrmMedico.setText(c.getMedico().getCrm_Medico());
            jLabelNomeMedico.setText(c.getMedico().getNome());
            jLabelEspecialidade.setText(c.getMedico().getEspecialidade().getNomeEspecialidade());
            jFormattedTextFieldDataConsulta.setText(c.getDataConsulta());
            jFormattedTextFieldHoraInicio.setText(c.getHoraInicio());
            jFormattedTextFieldHoraFinal.setText(c.getHoraFinal());
            jTextAreaRelatorio.setText(c.getDescricaoConsulta());   
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
  }
    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        try {
        mostrarProntuario();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jTextFieldCpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCpfPacienteActionPerformed

    private void jButtonRemoverProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverProntuarioActionPerformed
    try {
        int resp = JOptionPane.showConfirmDialog(null, "Voce deseja remover o prontuario?", "Remover Prontúario", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
        c.setNumeroProntuario(jTextFieldProntuario.getText());
        NegocioTeladeConsulta ntc = new NegocioTeladeConsulta();
        ntc.remover(c);
        LimparTela();
        ListarProntuario();
        jTextFieldProntuario.setText("");
    }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jButtonRemoverProntuarioActionPerformed

    private void jTextFieldCpfPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCpfPacienteFocusLost
try{
c.getPaciente().setCpf_Paciente(jTextFieldCpfPaciente.getText()); 
NegocioTeladeConsulta ntc = new NegocioTeladeConsulta();
ntc.ValidacaoCPF(c);
}
catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
}
try{
jLabelNomePaciente.setText(""+c.getPaciente().getNome());
jLabePlanodeSaude.setText(""+ c.getPaciente().getPlanodeSaude().getNomePlano());
}catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
}
    }//GEN-LAST:event_jTextFieldCpfPacienteFocusLost

    private void jTextFieldCrmMedicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCrmMedicoFocusLost
try{
c.getMedico().setCrm_Medico(jTextFieldCrmMedico.getText()); 
NegocioTeladeConsulta ntc = new NegocioTeladeConsulta();
ntc.ValidacaoCRM(c);
}
catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            jTextFieldCrmMedico.setText(" ");
            jLabelNomeMedico.setText(" ");
            jLabelEspecialidade.setText(" ");
}
try{
jLabelNomeMedico.setText(" "+ c.getMedico().getNome());
jLabelEspecialidade.setText(" "+ c.getMedico().getEspecialidade().getNomeEspecialidade());
}catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
}
    }//GEN-LAST:event_jTextFieldCrmMedicoFocusLost

    private void jButtonAtualizarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarProntuarioActionPerformed
    try {
        int resp = JOptionPane.showConfirmDialog(null, "Voce deseja atualizar o prontuario?", "Atualizar Prontúario", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
        NegocioTeladeConsulta ntc = new NegocioTeladeConsulta();
            c.getPaciente().setCpf_Paciente(jTextFieldCpfPaciente.getText());
            c.getMedico().setCrm_Medico(jTextFieldCrmMedico.getText());
            c.setDataConsulta(jFormattedTextFieldDataConsulta.getText());
            c.setHoraInicio(jFormattedTextFieldHoraInicio.getText());
            c.setHoraFinal(jFormattedTextFieldHoraFinal.getText());
            c.setDescricaoConsulta(jTextAreaRelatorio.getText()); 
        ntc.atualizar(c);
        ListarMedico();
    }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
    }//GEN-LAST:event_jButtonAtualizarProntuarioActionPerformed

    private void jTextFieldCrmMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrmMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrmMedicoActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeladeConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarProntuario;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonListagemMedico;
    private javax.swing.JButton jButtonListagemPaciente;
    private javax.swing.JButton jButtonListagemProntuario;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonRemoverProntuario;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataConsulta;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoraFinal;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoraInicio;
    private javax.swing.JLabel jLabePlanodeSaude;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEspecialidade;
    private javax.swing.JLabel jLabelNomeMedico;
    private javax.swing.JLabel jLabelNomePaciente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemRegistroEspecialidade;
    private javax.swing.JMenuItem jMenuItemRegistroMedico;
    private javax.swing.JMenuItem jMenuItemRegistroPaciente;
    private javax.swing.JMenuItem jMenuItemRegistroPlanodeSaude;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListagem;
    private javax.swing.JTextArea jTextAreaRelatorio;
    private javax.swing.JTextField jTextFieldCpfPaciente;
    private javax.swing.JTextField jTextFieldCrmMedico;
    private javax.swing.JTextField jTextFieldProntuario;
    // End of variables declaration//GEN-END:variables
}
